
// echo "pub const a = .{"; for f in $(find ~/.cache/zig/p/HASH/ | grep -Eo "source/.+"); do echo "    \"$f\","; done; echo "};"

pub const maxmod_arm7_asm = .{
    "source/mm_effect.s",
    "source/mm_main.s",
    "source/mm_mas.s",
    "source/mm_mas_arm.s",
    "source_ds7/mm_comms7.s",
    "source_ds7/mm_mixer_super.s",
    "source_ds7/mm_reverb.s",
    "source_ds7/mm_sleep.s",
};
pub const maxmod_arm9_asm = .{
    "source_ds9/mm_comms.s",
    "source_ds9/mm_flusher.s",
    "source_ds9/mm_main9.s",
    "source_ds9/mm_memory.s",
    "source_ds9/mm_soundbank.s",
};
pub const maxmod_common_asm = .{
    "source_ds/mm_stream.s",
};



pub const dswifi_arm7_c = .{
    "arm7/wifi_arm7.c",
};
pub const dswifi_arm9_c = .{
    "arm9/sgIP_ARP.c",
    "arm9/sgIP_TCP.c",
    "arm9/sgIP_memblock.c",
    "arm9/sgIP.c",
    "arm9/sgIP_UDP.c",
    "arm9/sgIP_ICMP.c",
    "arm9/sgIP_sockets.c",
    "arm9/sgIP_DHCP.c",
    "arm9/wifi_arm9.c",
    "arm9/sgIP_IP.c",
    "arm9/sgIP_DNS.c",
    "arm9/sgIP_Hub.c",
};
pub const dswifi_common_asm = .{
    "common/spinlock.s",
};



pub const fatfs_c = .{
    "ffunicode.c",
    "ff.c",
};
pub const grit_cpp = .{
    "cldib/cldib_adjust.cpp",
    "cldib/cldib_conv.cpp",
    "cldib/cldib_core.cpp",
    "cldib/cldib_tmap.cpp",
    "cldib/cldib_tools.cpp",
    "cldib/cldib_wu.cpp",
    "libgrit/cprs.cpp",
    "libgrit/cprs_huff.cpp",
    "libgrit/cprs_lz.cpp",
    "libgrit/cprs_rle.cpp",
    "libgrit/grit_core.cpp",
    "libgrit/grit_misc.cpp",
    "libgrit/grit_prep.cpp",
    "libgrit/grit_shared.cpp",
    "libgrit/grit_xp.cpp",
    "libgrit/logger.cpp",
    "libgrit/pathfun.cpp",
    "extlib/plum.cpp",
    "srcgrit/cli.cpp",
    "srcgrit/grit_main.cpp",
};

pub const ndstool_c = .{
    "loadme.c",
    "compile_date.c",
};
pub const ndstool_cpp = .{
    "ndstree.cpp",
    "header.cpp",
    "crc.cpp",
    "ndscodes.cpp",
    "raster.cpp",
    "utf16.cpp",
    "ndscreate.cpp",
    "logo.cpp",
    "bigint.cpp",
    "elf.cpp",
    "ndstool.cpp",
    "banner.cpp",
    "sha1.cpp",
    "ndsextract.cpp",
};

pub const squeezer_c = .{
    "imageops.c",
    "lodepng.c",
    "maxrects.c",
    "squeezer.c",
    "squeezerw.c",
};

pub const mmutil_c = .{
    "xm.c",
    "it.c",
    "mas.c",
    "s3m.c",
    "upload.c",
    "gba.c",
    "main.c",
    "simple.c",
    "mod.c",
    "samplefix.c",
    "wav.c",
    "adpcm.c",
    "kiwi.c",
    "msl.c",
    "nds.c",
    "files.c",
};

pub const libnds_arm9_c = .{
    "arm9/grf.c",
    "arm9/storage/card.c",
    "arm9/storage/sdmmc.twl.c",
    "arm9/storage/dldi.c",
    "arm9/storage/firmware.c",
    "arm9/trig.c",
    "arm9/math.c",
    "arm9/image.c",
    "arm9/teak/fifo.twl.c",
    "arm9/teak/process.twl.c",
    "arm9/teak/dsp.twl.c",
    "arm9/libc/fatfs.c",
    "arm9/libc/crt0_argv.c",
    "arm9/libc/filesystem.c",
    "arm9/libc/dirent.c",
    "arm9/libc/scandir.c",
    "arm9/libc/iob.c",
    "arm9/libc/fatfs/cache.c",
    "arm9/libc/fatfs/ffsystem.c",
    "arm9/libc/fatfs/diskio.c",
    "arm9/libc/statvfs.c",
    "arm9/libc/realpath.c",
    "arm9/libc/nitrofs.c",
    "arm9/libc/utime.c",
    "arm9/libc/chdir.c",
    "arm9/peripherals/camera.c",
    "arm9/peripherals/slot2.c",
    "arm9/peripherals/slot2solar.c",
    "arm9/peripherals/camera.twl.c",
    "arm9/peripherals/slot2gyro.c",
    "arm9/peripherals/piano.c",
    "arm9/peripherals/paddle.c",
    "arm9/peripherals/rumble.c",
    "arm9/peripherals/slot2.twl.c",
    "arm9/peripherals/ndsmotion.c",
    "arm9/peripherals/guitarGrip.c",
    "arm9/peripherals/slot2tilt.c",
    "arm9/system/initSystem.c",
    "arm9/system/cache.c",
    "arm9/system/exceptions.c",
    "arm9/system/system.c",
    "arm9/system/heapfuncs.c",
    "arm9/system/keys.c",
    "arm9/system/securearea.c",
    "arm9/system/gurumeditation.c",
    "arm9/sound.c",
    "arm9/video/video.c",
    "arm9/video/sprite_alloc.c",
    "arm9/video/shadowRegs.c",
    "arm9/video/videoGL.c",
    "arm9/video/gl2d.c",
    "arm9/video/sprite.c",
    "arm9/video/background.c",
    "arm9/video/boxtest.c",
    "arm9/video/window.c",
    "arm9/console.c",
    "arm9/linkedlist.c",
    //     "arm9/decompress.c",
    "arm9/sassert.c",
    "arm9/pcx.c",
    "arm9/dynamicArray.c",
    "arm9/keyboard.c",
};
pub const libnds_arm9_asm = .{
    "arm9/storage/dldi_stub.s",
    "arm9/teak/utils.twl.s",
    "arm9/system/IntrWait.s",
    "arm9/system/cp15.s",
    "arm9/system/vectorbase.s",
    "arm9/system/mpu_setup.s",
    "arm9/system/cpu_clock.s",
    "arm9/system/exceptionHandler.s",
};
pub const libnds_common_c = .{
    "common/cardEeprom.c",
    "common/nwram.twl.c",
    "common/debugprint.c",
    "common/decompress.c",
    "common/card.c",
    "common/rsa.c",
    "common/cothread/threads.c",
    "common/syscalls.c",
    "common/reset.c",
    "common/libc/syscalls.c",
    "common/libc/locks.c",
    "common/libc/exit.c",
    "common/libc/sbrk.c",
    "common/timers.c",
    "common/ndsabi/coroutine.c",
    "common/ndsabi/context.c",
    "common/interrupts.c",
    "common/sha1.c",
    "common/fifosystem.c",
};
pub const libnds_common_asm = .{
    "common/biosCalls.twl.s",
    "common/dma.s",
    "common/cothread/aeabi_read_tp.s",
    "common/swiSoftReset.s",
    "common/cpu.s",
    "common/ndsabi/rmemcpy.s",
    "common/ndsabi/memset.s",
    "common/ndsabi/context.s",
    "common/ndsabi/memcpy.s",
    "common/ndsabi/memmove.s",
    "common/ndsabi/fiq_memcpy.s",
    "common/ndsabi/coroutine.s",
    "common/interruptDispatcher.s",
    "common/biosCalls.s",
    "common/debugprint.s",
};
pub const libnds_arm7_c = .{
    "arm7/audio.c",
    "arm7/touch.c",
    "arm7/storage/sdmmc.twl.c",
    "arm7/storage/card.twl.c",
    "arm7/storage/storage_fifo.twl.c",
    "arm7/storage/storage_fifo.c",
    "arm7/camera.twl.c",
    "arm7/tmio.twl.c",
    "arm7/microphone.twl.c",
    "arm7/touchFilter.c",
    "arm7/libc/filesystem.c",
    "arm7/libc/iob.c",
    "arm7/i2c.twl.c",
    "arm7/system.c",
    "arm7/gpio.c",
    "arm7/clock.c",
    "arm7/microphone.c",
    "arm7/audio.twl.c",
    "arm7/camerai2c.twl.c",
    "arm7/input.c",
    "arm7/tsc.c",
    "arm7/systemShutDown.c",
    "arm7/spi.c",
    "arm7/codec.twl.c",
    "arm7/firmware.c",
    "arm7/userSettings.c",
};
pub const libnds_arm7_asm = .{
    "arm7/intrwait.s",
};
