// cd libnds
// find -L source -name "*.c" | grep -E -o arm9/.+
// find -L source -name "*.S | grep -E -o arm9/.+

// find -L source -name "*.c" | grep -E -o common/.+
// find -L source -name "*.S" | grep -E -o common/.+

// find -L source -name "*.c" | grep -E -o arm7/.+
// find -L source -name "*.S" | grep -E -o arm7/.+

pub const fatfs_c = .{
    "ffunicode.c",
    "ff.c",
};
pub const grit_cpp = .{
    "cldib/cldib_adjust.cpp",
    "cldib/cldib_conv.cpp",
    "cldib/cldib_core.cpp",
    "cldib/cldib_tmap.cpp",
    "cldib/cldib_tools.cpp",
    "cldib/cldib_wu.cpp",
    "libgrit/cprs.cpp",
    "libgrit/cprs_huff.cpp",
    "libgrit/cprs_lz.cpp",
    "libgrit/cprs_rle.cpp",
    "libgrit/grit_core.cpp",
    "libgrit/grit_misc.cpp",
    "libgrit/grit_prep.cpp",
    "libgrit/grit_shared.cpp",
    "libgrit/grit_xp.cpp",
    "libgrit/logger.cpp",
    "libgrit/pathfun.cpp",
    "extlib/plum.cpp",
    "srcgrit/cli.cpp",
    "srcgrit/grit_main.cpp",
};

pub const ndstool_c = .{
    "loadme.c",
    "compile_date.c",
};
pub const ndstool_cpp = .{
    "ndstree.cpp",
    "header.cpp",
    "crc.cpp",
    "ndscodes.cpp",
    "raster.cpp",
    "utf16.cpp",
    "ndscreate.cpp",
    "logo.cpp",
    "bigint.cpp",
    "elf.cpp",
    "ndstool.cpp",
    "banner.cpp",
    "sha1.cpp",
    "ndsextract.cpp",
};

pub const squeezer_c = .{
    "imageops.c",
    "lodepng.c",
    "maxrects.c",
    "squeezer.c",
    "squeezerw.c",
};

pub const mmutil_c = .{
    "xm.c",
    "it.c",
    "mas.c",
    "s3m.c",
    "upload.c",
    "gba.c",
    "main.c",
    "simple.c",
    "mod.c",
    "samplefix.c",
    "wav.c",
    "adpcm.c",
    "kiwi.c",
    "msl.c",
    "nds.c",
    "files.c",
};

pub const libnds_arm9_c = .{
    "arm9/grf.c",
    "arm9/storage/card.c",
    "arm9/storage/sdmmc.twl.c",
    "arm9/storage/dldi.c",
    "arm9/storage/firmware.c",
    "arm9/trig.c",
    "arm9/math.c",
    "arm9/image.c",
    "arm9/teak/fifo.twl.c",
    "arm9/teak/process.twl.c",
    "arm9/teak/dsp.twl.c",
    "arm9/libc/fatfs.c",
    "arm9/libc/crt0_argv.c",
    "arm9/libc/filesystem.c",
    "arm9/libc/dirent.c",
    "arm9/libc/scandir.c",
    "arm9/libc/iob.c",
    "arm9/libc/fatfs/cache.c",
    "arm9/libc/fatfs/ffsystem.c",
    "arm9/libc/fatfs/diskio.c",
    "arm9/libc/statvfs.c",
    "arm9/libc/realpath.c",
    "arm9/libc/nitrofs.c",
    "arm9/libc/utime.c",
    "arm9/libc/chdir.c",
    "arm9/peripherals/camera.c",
    "arm9/peripherals/slot2.c",
    "arm9/peripherals/slot2solar.c",
    "arm9/peripherals/camera.twl.c",
    "arm9/peripherals/slot2gyro.c",
    "arm9/peripherals/piano.c",
    "arm9/peripherals/paddle.c",
    "arm9/peripherals/rumble.c",
    "arm9/peripherals/slot2.twl.c",
    "arm9/peripherals/ndsmotion.c",
    "arm9/peripherals/guitarGrip.c",
    "arm9/peripherals/slot2tilt.c",
    "arm9/system/initSystem.c",
    "arm9/system/cache.c",
    "arm9/system/exceptions.c",
    "arm9/system/system.c",
    "arm9/system/heapfuncs.c",
    "arm9/system/keys.c",
    "arm9/system/securearea.c",
    "arm9/system/gurumeditation.c",
    "arm9/sound.c",
    "arm9/video/video.c",
    "arm9/video/sprite_alloc.c",
    "arm9/video/shadowRegs.c",
    "arm9/video/videoGL.c",
    "arm9/video/gl2d.c",
    "arm9/video/sprite.c",
    "arm9/video/background.c",
    "arm9/video/boxtest.c",
    "arm9/video/window.c",
    "arm9/console.c",
    "arm9/linkedlist.c",
//     "arm9/decompress.c",
    "arm9/sassert.c",
    "arm9/pcx.c",
    "arm9/dynamicArray.c",
    "arm9/keyboard.c",
};
pub const libnds_arm9_asm = .{
    "arm9/storage/dldi_stub.S",
    "arm9/teak/utils.twl.S",
    "arm9/system/IntrWait.S",
    "arm9/system/cp15.S",
    "arm9/system/vectorbase.S",
    "arm9/system/mpu_setup.S",
    "arm9/system/cpu_clock.S",
    "arm9/system/exceptionHandler.S",
};
pub const libnds_common_c = .{
    "common/cardEeprom.c",
    "common/nwram.twl.c",
    "common/debugprint.c",
    "common/decompress.c",
    "common/card.c",
    "common/rsa.c",
    "common/cothread/threads.c",
    "common/syscalls.c",
    "common/reset.c",
    "common/libc/syscalls.c",
    "common/libc/locks.c",
    "common/libc/exit.c",
    "common/libc/sbrk.c",
    "common/timers.c",
    "common/ndsabi/coroutine.c",
    "common/ndsabi/context.c",
    "common/interrupts.c",
    "common/sha1.c",
    "common/fifosystem.c",
};
pub const libnds_common_asm = .{
    "common/biosCalls.twl.S",
    "common/dma.S",
    "common/cothread/aeabi_read_tp.S",
    "common/swiSoftReset.S",
    "common/cpu.S",
    "common/ndsabi/rmemcpy.S",
    "common/ndsabi/memset.S",
    "common/ndsabi/context.S",
    "common/ndsabi/memcpy.S",
    "common/ndsabi/memmove.S",
    "common/ndsabi/fiq_memcpy.S",
    "common/ndsabi/coroutine.S",
    "common/interruptDispatcher.S",
    "common/biosCalls.S",
    "common/debugprint.S",
};
pub const libnds_arm7_c = .{
    "arm7/audio.c",
    "arm7/touch.c",
    "arm7/storage/sdmmc.twl.c",
    "arm7/storage/card.twl.c",
    "arm7/storage/storage_fifo.twl.c",
    "arm7/storage/storage_fifo.c",
    "arm7/camera.twl.c",
    "arm7/tmio.twl.c",
    "arm7/microphone.twl.c",
    "arm7/touchFilter.c",
    "arm7/libc/filesystem.c",
    "arm7/libc/iob.c",
    "arm7/i2c.twl.c",
    "arm7/system.c",
    "arm7/gpio.c",
    "arm7/clock.c",
    "arm7/microphone.c",
    "arm7/audio.twl.c",
    "arm7/camerai2c.twl.c",
    "arm7/input.c",
    "arm7/tsc.c",
    "arm7/systemShutDown.c",
    "arm7/spi.c",
    "arm7/codec.twl.c",
    "arm7/firmware.c",
    "arm7/userSettings.c",
};
pub const libnds_arm7_asm = .{
    "arm7/intrwait.S",
};